name: Build Binary

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04   # 👈 IMPORTANT (older GLIBC)

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install GCC
      run: sudo apt update && sudo apt install -y gcc

    - name: Compile
      run: gcc -o ddos ddos.c -lpthread -O2

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: ddos-binary
        path: ddos
